import streamlit as SL

def usage():
    SL.markdown("### HOW TO USE")
    SL.markdown("#### API KEYS")
    SL.markdown("Please enter your **Google AI Studio** API keys in the **API Configuration** section to interact with this project.<br />Get your Google API keys here: [https://aistudio.google.com/api-keys](https://aistudio.google.com/api-keys).<br /><br />Creating multiple API keys directly in Google AI Studio will not help as these keys will use tokens from the same bucket.<br />In order to increase usage limits, please create separate individual projects in **Google Cloud**.<br />Create your Google Cloud project here: [https://console.cloud.google.com/projectcreate](https://console.cloud.google.com/projectcreate).<br /><br />Find the guide to creating a new Google Cloud project here: [https://developers.google.com/workspace/guides/create-project](https://developers.google.com/workspace/guides/create-project)<br /><br />Google Cloud project dashboard: [https://console.cloud.google.com/home/dashboard](https://console.cloud.google.com/home/dashboard).<br />In the top left corner, click the button to the right of **Google Cloud**/**Menu** in the screen to navigate to different projects.<br /><br />After that, go to [https://aistudio.google.com/projects](https://aistudio.google.com/projects), click on the 'refresh' icon and click on **Import projects** in the top right corner. Import your Google Cloud projects one by one.<br />Now go back to the **API keys** section in Google AI Studio and *when creating a **new** key, select a different project each time* from the **Choose an imported project** dropdown menu in the **Create a new key** dialog box. This way, there will be more credits and work will not be interrupted due to sudden token exhaustion.", unsafe_allow_html=True)
    SL.markdown("#### TABS")
    SL.markdown("The **Chat** tab is a simple chat interface to ask the AI your doubts and get answers.<br /><br />The **Timetable** tab can be used to generate a simple timetable based on your requirements. Please enter the task name for each task and the total duration of your work to generate a timetable. The remaining details for each task are optional.<br /><br />For the remaining tabs, please upload a digital or document or an image to get results, explanations, summaries, key words, answers, or related documents/images/sources of information.<br />Documents/images may be digital or photos of manually handwritten or handdrawn work.<br /><br />The following file types are accepted: .jpg, .jpeg, .png, .doc, .docx, .pdf, .xlsx, .txt, .pptx.", unsafe_allow_html=True)


